Add: ceph.client manila definition
osism/ansible-defaults pull request #119
Opened 2023-03-23 13:14 UTC by matfechner

2023-03-27 07:29 UTC, osfrickler commented on all/099-ceph.yml
> +      osd: "profile rbd pool={{ cephfs_data_pool.name }}"
Are you sure about the "profile rbd" part? In the manila docs this looks different https://docs.openstack.org/manila/latest/admin/cephfs_driver.html#authorizing-the-driver-to-communicate-with-ceph

2023-04-19 08:52 UTC, ppkuschy requested changes
Client Caps need to be adjusted

2023-04-19 08:52 UTC, ppkuschy commented on all/099-ceph.yml
> +      mon: "profile rbd"
```suggestion
      mon: "allow r"
      mgr: "allow rw"
```

2023-06-29 11:25 UTC, ppkuschy approved these changes
LGTM

2023-06-30 06:49 UTC, merged